trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'SelfHostedPool'  # 🔹 Replace with your actual self-hosted agent pool name

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      echo "🔹 Setting up Git user config..."
      git config --global user.email "your-email@example.com"
      git config --global user.name "Azure DevOps"

      echo "🔹 Checking for ongoing rebase..."
      if [ -d ".git/rebase-merge" ] || [ -d ".git/rebase-apply" ]; then
          echo "🔹 Aborting previous rebase..."
          git rebase --abort
      fi

      echo "🔹 Fetching latest changes from origin..."
      git fetch --all --prune

      echo "🔹 Checking out 'main' branch..."
      git checkout main

      echo "🔹 Pulling latest changes from origin..."
      git pull --rebase origin main || (git reset --hard origin/main)

      echo "🔹 Ensuring external GitHub remote is set up..."
      if git remote get-url external >/dev/null 2>&1; then
          echo "🔹 External remote already exists. Updating URL..."
          git remote set-url external https://$(GITHUB_PAT)@github.com/Premal2002/OnlineBookStoreFrontend.git
      else
          echo "🔹 Adding external GitHub remote..."
          git remote add external https://$(GITHUB_PAT)@github.com/Premal2002/OnlineBookStoreFrontend.git
      fi

      echo "🔹 Fetching latest from external GitHub repo..."
      git fetch external --prune

      echo "🔹 Forcing push to external GitHub repository..."
      git push external main --force

    displayName: 'Pull and Push changes to external Git repository'