trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'SelfHostedPool'  # 🔹 Replace with your actual self-hosted agent pool name

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      echo "🔹 Setting up Git user config..."
      git config --global user.email "your-email@example.com"
      git config --global user.name "Azure DevOps"

      echo "🔹 Fetching latest changes from origin..."
      git fetch origin main --depth=1

      echo "🔹 Checking out and ensuring 'main' branch exists..."
      git checkout main 2>nul || git checkout -b main origin/main

      echo "🔹 Merging latest changes to resolve divergence..."
      git merge origin/main --no-edit || (
        echo "⚠️ Merge conflict detected, attempting rebase..."
        git rebase origin/main || (
          echo "❌ Automatic rebase failed. Please resolve conflicts manually."
          exit /b 1
        )
      )

      echo "🔹 Configuring GitHub remote..."
      git remote -v | findstr /C:"external" > nul
      if %errorlevel% neq 0 (
        echo "✅ Adding external GitHub remote..."
        git remote add external https://$(GITHUB_PAT)@github.com/Premal2002/OnlineBookStoreFrontend.git
      ) else (
        echo "✅ External remote already exists. Updating..."
        git remote set-url external https://$(GITHUB_PAT)@github.com/Premal2002/OnlineBookStoreFrontend.git
      )

      echo "🔹 Pushing to external GitHub repository..."
      git push external main || (
        echo "⚠️ Push failed. Trying force push..."
        git push external main --force
      )

    displayName: 'Push changes to external Git repository'
