trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'SelfHostedPool'  # 🔹 Replace with your actual self-hosted agent pool name

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      echo "🔹 Setting up Git user config..."
      git config --global user.email "your-email@example.com"
      git config --global user.name "Azure DevOps"

      echo "🔹 Fetching latest changes from origin..."
      git fetch --all --prune

      echo "🔹 Checking out 'main' branch..."
      git checkout main

      echo "🔹 Pulling latest changes from origin..."
      git pull --rebase origin main || (git reset --hard origin/main)

      echo "🔹 Ensuring external GitHub remote is set up..."
      git remote remove external 2>/dev/null || echo "No previous external remote."
      git remote add external https://$(GITHUB_PAT)@github.com/Premal2002/OnlineBookStoreFrontend.git

      echo "🔹 Pushing changes to external GitHub repository..."
      git push external main --force

    displayName: 'Pull and Push changes to external Git repository'


