trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'SelfHostedPool'  # 🔹 Replace with your actual self-hosted agent pool name

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      echo "🔹 Setting up Git user config..."
      git config --global user.email "your-email@example.com"
      git config --global user.name "Azure DevOps"

      echo "🔹 Fetching latest changes from origin..."
      git fetch --all --prune

      echo "🔹 Resetting branch to match remote..."
      git checkout main
      git reset --hard origin/main  # 🔹 Forces local branch to match Azure's version

      echo "🔹 Configuring external GitHub remote..."
      git remote -v | findstr /C:"external" > nul
      if %errorlevel% neq 0 (
        echo "✅ Adding external GitHub remote..."
        git remote add external https://$(GITHUB_PAT)@github.com/Premal2002/OnlineBookStoreFrontend.git
      ) else (
        echo "✅ External remote already exists. Updating..."
        git remote set-url external https://$(GITHUB_PAT)@github.com/Premal2002/OnlineBookStoreFrontend.git
      )

      echo "🔹 Pushing to external GitHub repository..."
      git push external main --force  # 🔹 Force push to overwrite any conflicts

    displayName: 'Push changes to external Git repository'

