trigger: none  # No automatic build on commits

pool:
  name: 'SelfHostedPool'  # 🔹 Replace with your actual self-hosted agent pool name

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'  # Ensure this matches your Angular setup
    displayName: "Set up Node.js"

  - script: |
      npm ci
    displayName: "Install Dependencies"

  - script: |
      npm run build -- --configuration=production
    displayName: "Build Angular App"
